defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e27274f4-a9db-432d-9f4e-528bc6445874 # Page entry
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  837013f5-b45d-4d7b-ba35-7b49e35ecc95: # Accounting
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
